[package]
name = "gate-render"
edition.workspace = true
version.workspace = true
license.workspace = true

[features]
profile = ["dep:wgpu-profiler"]

[dependencies]
bevy = { workspace = true, features = ["jpeg"] }
glam = { workspace = true }
gate-voxel = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
ron = { workspace = true }
wgpu-profiler = { workspace = true, optional = true }
wesl = { workspace = true }
wgpu = { version = "=30.0.1", default-features = false }

[dev-dependencies]
naga = { version = "=30.0.1", default-features = false, features = ["wgsl-in"] }
