[package]
name = "gate-app"
edition.workspace = true
version.workspace = true
license.workspace = true

[package.metadata.i18n]
available-locales = ["zh-CN"]
default-locale = "zh-CN"
load-path = "../assets/locales"

[features]
profile = [
  "gate-render/profile",
  "bevy/trace",
  "dep:tracy-client",
]

[dependencies]
bevy = { workspace = true, features = ["png"] }
glam = { workspace = true }
gate-voxel = { workspace = true }
gate-render = { workspace = true }
gate-ui = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3.20", features = ["time"] }
tracing-appender = "0.2"
tracy-client = { workspace = true, optional = true }
time = { version = "0.3", features = ["formatting", "local-offset"] }
vox-rs = "0.2.0"
rayon = { workspace = true }
fastnbt = { workspace = true }
fastanvil = { workspace = true }
flate2 = { workspace = true }
png = { workspace = true }
serde_json = { workspace = true }
rust-i18n = "4.2"
serde = { workspace = true }
toml = "0.8"
